config/routes.rb
#require 'tail'

ContentManagement::Application.routes.draw do
  resources :video_files

  get "stats/choose_dates"
  get "stats/results"
  devise_for :users

  get 'redirector', to: 'outgrader#get_redirect', format: 'js'
  #get 'outgrader/get_redirect'
  get 'outgrader' => 'outgrader#index'
  get 'outgrader/start'
  get 'outgrader/stop'
  get 'outgrader/restart'
  get 'outgrader/kill'
  get 'outgrader/get_config'
  post 'outgrader/outgrader_change_ip'
  post 'outgrader/redirector_change_ip'
  post 'outgrader/change_config'

  #get 'visits/send_click'
  post 'visits/send_click'
  get 'visits' => 'visits#index'
  #get 'visits/send_visit'
  post 'visits/send_visit'
  get 'visits/downloads'
  get 'visits/most_wanted'
  get 'visits/graph'
  get 'visits/torrents'


  mount Tail::Engine, at: '/tail'

  resources :sites

  resources :links

  resources :contents do
    member do
      post 'add_link' => 'contents#add_link'

    end
    collection do
      get 'create_with_kinopoisk' => 'contents#create_with_kinopoisk'
    end
  end

  root 'contents#index'

end

app/models/content.rb
require 'open-uri'
require 'nokogiri'

class Content < ActiveRecord::Base
  has_many :links, dependent: :destroy
  has_many :sites, through: :links
  has_many :video_files, dependent: :destroy
  validates :name, presence: true

  USER_AGENTS = ['Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/33.0.1750.146 Safari/537.36',
                 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_1) AppleWebKit/537.73.11 (KHTML, like Gecko) Version/7.0.1 Safari/537.73.11',
                 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/32.0.1700.102 Safari/537.36 OPR/19.0.1326.59',
                 'Opera/9.80 (Windows NT 5.1; U; en) Presto/2.2.15 Version/10.10',
                 'Mozilla/5.0 (X11; U; Linux i686; de; rv:1.9.1.5) Gecko/20091112 Iceweasel/3.5.5 (like Firefox/3.5.5; Debian-3.5.5-1)']


  def self.text_search(query)
    query.present? ? search(query) : all
  end

  def self.find_content(url, site)
    url+='/' unless url.end_with?('/')

    html = Nokogiri::HTML open(url, 'User-Agent' => Content::USER_AGENTS.sample)
    name = html.at_css(site.name_css).content
    year = html.at_css(site.year_css).content

    content = Content.text_search("#{name}, #{year}").first
    site.links.create(url: url, content: content) if content.present?

    return content
  rescue => e
    logger.error url
    logger.error e.message
    logger.error e.backtrace[0..3]
    return nil
  end

  def self.create_with_kinopoisk(link)
    link+='/' unless link.end_with?('/')

    html = Nokogiri::HTML open(link, 'User-Agent' => Content::USER_AGENTS.sample)
    info = html.at_css('.info')
    info.css('a').each do |a|
      a[:href] = 'http://www.kinopoisk.ru' + a[:href] if a[:href].present? && a[:href].start_with?('/')
      a[:target] = '_blank'
    end
    info = info.to_html.encode('utf-8')

    rating = html.at_css('.block_2')
    if rating.present?
      rating.css('a').each do |a|
        a[:href] = 'http://www.kinopoisk.ru' + a[:href] if a[:href].present? && a[:href].start_with?('/')
        a[:target] = '_blank'
      end
      rating = rating.to_html.encode('utf-8')
    end

    description = html.at_css('._reachbanner_ .brand_words')
    description = description.to_html.encode('utf-8') if description.present?

    image = "http://www.kinopoisk.ru/images/film/#{link[/\d+/]}.jpg"

    name = html.at_css('title').content
    year = html.at_css('#infoTable tr:nth-child(1) a').content

    content = Link.find_by(url: link).present? ? Link.find_by(url: link).content : Content.new
    content.info = info
    content.rating = rating
    content.description = description
    content.image = image
    content.name = "#{name}, #{year}"
    content.save
    content.links.create(url: link, site: Site.find_by(name: 'kinopoisk.ru'))
    return content
  rescue => e
    logger.error [link, e.message, e.backtrace]
    nil
  end
end

app/controllers/contents_controller.rb
require 'will_paginate/array'

class ContentsController < ApplicationController
  before_filter :authenticate_user!, except: [:index, :show]
  before_action :set_content, only: [:show, :edit, :update, :destroy, :add_link]

  # GET /contents
  # GET /contents.json
  def index
    @contents = Content.text_search(params[:query]).sort_by(&:name).paginate(page: params[:page], per_page: 30)
  end

  # GET /contents/1
  # GET /contents/1.json
  def show
  end

  def add_link
    url = params[:external_link].strip
    url+='/' unless url.end_with?('/')
    site = Link.find_site(url)
    if site.nil?
      redirect_to content_path(@content), alert: 'Сайт для этой ссылки не найден в базе'
      return
    else
      begin
        @content.links.create(url: url, site: site, content: @content)
      rescue => e
        redirect_to content_path(@content), alert: e.message
        return
      end
      redirect_to content_path(@content), notice: 'Добавлена'
    end

  end

  # GET /contents/new
  def new
    @content = Content.new
  end

  def create_with_kinopoisk
    redirect_to contents_path, notice: 'Фильм добавлен в базу.' if Content.create_with_kinopoisk(params[:kinopoisk]).present?
  end

  # GET /contents/1/edit
  def edit
  end

  # POST /contents
  # POST /contents.json
  def create
    @content = Content.new(content_params)
    @content.url+='/' unless @content.url.end_with?('/')
    respond_to do |format|
      if @content.save
        format.html { redirect_to @content, notice: 'Запись о файле создана.' }
        format.json { render action: 'show', status: :created, location: @content }
      else
        format.html { render action: 'new' }
        format.json { render json: @content.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contents/1
  # PATCH/PUT /contents/1.json
  def update
    respond_to do |format|
      if @content.update(content_params)
        @content.update(url: @content.url+'/') unless @content.url.end_with?('/')
        format.html { redirect_to @content, notice: 'Сведения о файле сохранены.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @content.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contents/1
  # DELETE /contents/1.json
  def destroy
    @content.destroy
    respond_to do |format|
      format.html { redirect_to contents_url }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_content
    @content = Content.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def content_params
    params.require(:content).permit(:name, :url)
  end
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/views/contents/_admin.html.haml
%strong
  = @content.name
(
= @content.url
)
= link_to 'Изменить', edit_content_path(@content), :class => 'btn btn-mini'
= link_to 'Назад', contents_path, :class => 'btn btn-mini'

%hr

= form_tag add_link_content_path, class: 'form-horizontal' do
  = label_tag 'Добавить ссылку'
  = text_field_tag :external_link, nil, class: 'span7'
  = submit_tag 'Добавить', class: 'btn'


%hr

%table.table.table-striped.table-condensed
  %thead
    %tr
      %th Внешние ссылки
      %th Действия
  %tbody
    - @content.links.order(:url).each do |link|
      %tr
        %td
          = link_to link.url, link.url, target: '_blank'
        %td
          = link_to 'Изменить', edit_link_path(link), class: 'btn btn-mini'
          = link_to 'Удалить', link_path(link), method: :delete, class: 'btn btn-mini'

%hr

%table.table.table-striped.table-condensed
  %thead
    %tr
      %th Файлы
      %th Качество
      %th Размер, ГБ
  %tbody
    - @content.video_files.order(:internal_name).uniq.each do |file|
      %tr
        %td
          = link_to file.internal_name, file.internal_url
        %td
          = file.quality
          %td
            = file.size

%table.table.table-striped.table-condensed
  %thead
    %tr
      %th Сайты
  %tbody
    - @content.sites.order(:name).uniq.each do |site|
      %tr
        %td
          = site.name

app/views/contents/_form.html.haml
= form_for @content, :html => { :class => 'form-horizontal' } do |f|
  .control-group
    = f.label 'Название', :class => 'control-label'
    .controls
      = f.text_field :name, :class => 'text_field span8'
  .control-group
    = f.label 'Внутренняя ссылка', :class => 'control-label'
    .controls
      = f.text_field :url, :class => 'text_field span8'
  .form-actions
    = f.submit 'Сохранить', :class => 'btn btn-primary'
    = link_to 'Отменить', contents_path, :class => 'btn'

app/views/contents/edit.html.haml
- model_class = Content
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/contents/index.html.haml
= content_for :title, 'Внутренняя сеть'
%h3 Фильмы во внутренней сети

=form_tag contents_path, class: 'form-horizontal', method: :get do
  .input-prepend
    %span.add-on
      %i.icon-search
    =text_field_tag :query, params[:query], class: 'span7'
  =submit_tag '', style: 'display: none'

%table.table.table-striped
  %thead
    %tr
      %th Название
      %th
      %th Кол-во файлов
  %tbody
    - @contents.each do |content|
      %tr
        %td= link_to content.name, content_path(content), style: 'vertical-align: middle;'
        %td
          - if content.video_files.size > 1
            - sign = 'Выбрать'
            - url = content_path(content)
          - if content.video_files.size == 1
            - sign = 'Скачать'
            - url = content.video_files.first.internal_url
          - if content.video_files.empty?
            - sign = 'Посмотреть информацию'
            - url = content_path(content)
          =link_to sign, url, class: 'btn btn-small btn-info'
        %td= content.video_files.count
        -if user_signed_in?
          %td
            = link_to 'Изменить', edit_content_path(content), :class => 'btn btn-mini'
            = link_to 'Добавить ссылки', content_path(content), :class => 'btn btn-mini'
            = link_to 'Удалить', content_path(content), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-mini'

.paginate.pagination-centered
  =will_paginate @contents
-if user_signed_in?
  = link_to 'Добавить новый', new_content_path, :class => 'btn btn-primary'

app/views/contents/new.html.haml
%h3 Добавить файл

= form_tag create_with_kinopoisk_contents_path, method: :get, class: 'form-horizontal' do
  = text_field_tag :kinopoisk
  = submit_tag 'Добавить', class: 'btn'

app/views/contents/show.html.haml
= content_for :title, @content.name

-if user_signed_in?
  = render partial: 'admin'

.row
  .span2
    -if @content.image.present?
      = image_tag @content.image.html_safe, class: :icon
  .span4
    %h4
      = @content.name
    -if @content.description.present?
      =@content.description.html_safe
  .span2#rating
    Рейтинг
    -if @content.rating.present?
      =@content.rating.html_safe
%br
.row
  .span6
    -if @content.info.present?
      =@content.info.html_safe
  .span6
    -unless @content.video_files.empty?
      .muted.centered
        Этот фильм есть во внутренней сети
      %h3.centered
        Скачать
      -@content.video_files.each do |file|
        =link_to "#{file.internal_name} (#{file.size}ГБ, #{file.quality})", file.internal_url, class: 'btn btn-info download'