config/routes.rb
#require 'tail'

ContentManagement::Application.routes.draw do
  resources :video_files

  get "stats/choose_dates"
  get "stats/results"
  devise_for :users

  get 'redirector', to: 'outgrader#get_redirect', format: 'js'
  #get 'outgrader/get_redirect'
  get 'outgrader' => 'outgrader#index'
  get 'outgrader/start'
  get 'outgrader/stop'
  get 'outgrader/restart'
  get 'outgrader/kill'
  get 'outgrader/get_config'
  post 'outgrader/outgrader_change_ip'
  post 'outgrader/redirector_change_ip'
  post 'outgrader/change_config'

  #get 'visits/send_click'
  post 'visits/send_click'
  get 'visits' => 'visits#index'
  #get 'visits/send_visit'
  post 'visits/send_visit'
  get 'visits/downloads'
  get 'visits/most_wanted'
  get 'visits/graph'
  get 'visits/torrents'


  mount Tail::Engine, at: '/tail'

  resources :sites

  resources :links

  resources :contents do
    member do
      post 'add_link' => 'contents#add_link'

    end
    collection do
      get 'create_with_kinopoisk' => 'contents#create_with_kinopoisk'
    end
  end

  root 'contents#index'

end

app/models/visit.rb
require 'nokogiri'
require 'open-uri'

class Visit < ActiveRecord::Base
  belongs_to :link

  def self.stats(from=nil, to=nil)
    if from.present? && to.present?
      full_list = Visit.where(link_id: nil, time: [from..to]).pluck(:film)
    else
      full_list = Visit.where(link_id: nil).pluck(:film)
    end
    short_list = full_list.uniq

    short_list.map{|film| [film, full_list.count(film)]}.sort_by{|film| film[1]}.reverse
  end

  def self.get_torrents
    html = Nokogiri::HTML open 'http://kinozal.tv/top.php'
    films = html.css '.stable a'
    torrents = Array.new(films.size){{}}
    films.each_with_index do |film, i|
      title = film[:title]
      torrents[i][:name] = title.split('/').first.strip
      torrents[i][:year] = title[/\d{4,}/]
      torrents[i][:quality] = title.split('/').last.strip

      content = Content.find_by(name: "#{torrents[i][:name]}, #{torrents[i][:year]}")
      if content.nil?
        content = Content.find_by(name: "#{torrents[i][:name]}, #{torrents[i][:year].to_i-1}")
      end
      if content.nil?
        content = Content.find_by(name: "#{torrents[i][:name]}, #{torrents[i][:year].to_i+1}")
      end
      torrents[i][:files_number] = content.present? ? content.video_files.size : 0
    end
    torrents.select! {|torrent| VideoFile::QUALITIES.include? torrent[:quality]}
    torrents.sort_by! {|torrent| torrent[:files_number]}
  end
end

app/controllers/visits_controller.rb
require 'will_paginate/array'

class VisitsController < ApplicationController
  before_filter :authenticate_user!, only: [:index, :downloads, :most_wanted]
  skip_before_action :verify_authenticity_token, only: [:send_click, :send_visit]

  def index
    @visits = Visit.order(time: :desc).paginate(page: params[:page], per_page: 50)
  end

  def graph
    all_visits = Visit.all
    @hourly_stats = Array.new(24) {{}}
    @hourly_stats.each_with_index do |a, i|
      a[:hour] = i.to_s + ':00'
      visits = all_visits.select {|visit| visit.time.hour == i}
      a[:visits] = visits.count
      a[:downloads] = visits.select {|visit| visit.is_click? }.count
      a[:users] = visits.map(&:remote_ip).uniq.count
    end

    day_of_weeks = %w[Пон Вт Ср Чт Пт Сб Вс]
    @daily_stats = Array.new(7){{}}
    @daily_stats.each_with_index do |a, i|
      a[:day] = day_of_weeks[i]
      visits = all_visits.select {|visit| visit.time.wday == i}
      a[:visits] = visits.count
      a[:downloads] = visits.select {|visit| visit.is_click? }.count
      a[:users] = visits.map(&:remote_ip).uniq.count
    end

    @weekly_stats = Array.new(52){{}}
    @weekly_stats.each_with_index do |a, i|
      a[:week] = i
      visits = all_visits.select {|visit| visit.time.to_datetime.cweek == i}
      a[:visits] = visits.count
      a[:downloads] = visits.select {|visit| visit.is_click? }.count
      a[:users] = visits.map(&:remote_ip).uniq.count
    end
  end

  def torrents
    @torrents = Visit.get_torrents
  end

  def downloads
    @visits = Visit.where(is_click: true).order(time: :desc).paginate(page: params[:page], per_page: 50)
    render action: :index
  end

  def most_wanted
    @list = Visit.stats(params[:from], params[:to]).paginate(page: params[:page], per_page: 10)
  end

  def send_click
    params[:url] = 'http://www.kinopoisk.ru/film/77331/' if params[:url].nil?
    link = Link.find_by(url: params[:url])
    Visit.create(remote_ip: @_env["HTTP_X_FORWARDED_FOR"] || @_env["REMOTE_ADDR"], time: Time.now.to_formatted_s(:short), link: link, is_click: true) unless link.nil?

    response.headers['Access-Control-Allow-Origin'] = '*'
    render text: "click from #{@_env["HTTP_X_FORWARDED_FOR"]},  #{@_env["REMOTE_ADDR"]}", status: :ok
  end

  def send_visit
    params[:url] = 'http://www.kinopoisk.ru/film/77331/' if params[:url].nil?
    link = Link.find_by(url: params[:url])
    Visit.create(remote_ip: @_env["HTTP_X_FORWARDED_FOR"] || @_env["REMOTE_ADDR"],
                 time: Time.now.to_formatted_s(:short), link: link,
                 is_click: false, url: params[:url],
                 film: params[:name] + ', ' + params[:year]) #if params[:url].start_with? 'http://www.kinopoisk.ru/film' #TODO remove hardcode

    response.headers['Access-Control-Allow-Origin'] = '*'
    render text: "visit from #{@_env["HTTP_X_FORWARDED_FOR"]},  #{@_env["REMOTE_ADDR"]}", status: :ok
  end
end

app/helpers/visits_helper.rb
module VisitsHelper
end

app/views/visits/graph.html.haml
%h5.centered Часы
= content_for :title, 'Графики'
=content_tag :div, '', id: 'hourly_stats', data: {visits: @hourly_stats}

%hr
%h5.centered Дни недели
=content_tag :div, '', id: 'daily_stats', data: {visits: @daily_stats}

%hr
%h5.centered Недели
=content_tag :div, '', id: 'weekly_stats', data: {visits: @weekly_stats}

app/views/visits/index.html.haml
= content_for :title, 'Статистика'

=link_to 'Графики', visits_graph_path

.paginate.pagination-centered
  =will_paginate @visits

%table.table.table-striped.table-condensed
  %thead
    %tr
      %th Название
      %th Фильм/Сайт
      %th Дата
      %th IP
  %tbody
    -@visits.each do |visit|
      %tr{class: visit.is_click? ? 'success' : ''}
        -if visit.is_click? || visit.link.present?
          %td= visit.link.content.name
          %td{title: visit.link.url, class: 'tt'}= visit.link.site.name
          %td= visit.time.to_formatted_s(:short)
          %td= visit.remote_ip
        -else
          %td= link_to visit.url || 'localhost', visit.url
          %td= visit.film
          %td= visit.time.to_formatted_s(:short)
          %td= visit.remote_ip

= link_to 'К списку сайтов', sites_path, class: 'btn'
= link_to 'К списку файлов', contents_path, class: 'btn'

-#= link_to 'Статистика посещений', stats_choose_dates_path, class: 'btn'

.paginate.pagination-centered
  =will_paginate @visits

app/views/visits/most_wanted.html.haml
= content_for :title, 'Most wanted'

=link_to 'Всего', visits_most_wanted_path
|
=link_to 'За месяц', visits_most_wanted_path(from: Time.current - 1.month, to: Time.current)

%h4 Most wanted
%table.table.table-striped.table-condensed
  %thead
    %tr
      %th Название
      %th Кол-во запросов
  %tbody
    -@list.each do |film|
      %tr
        %td
          =film[0]
        %td
          =film[1]

.paginate.pagination-centered
  =will_paginate @list

app/views/visits/torrents.html.haml
%table.table
  %thead
    %th Название
    %th Кол-во файлов в базе
    %th Качество

  %tbody
    - @torrents.each do |torrent|
      -row_class = torrent[:files_number] == 0 ? 'error' : ''
      %tr{class: row_class }
        %td
          -if torrent[:files_number] > 0
            %i.icon-ok{style: 'color: green;'}
          ="#{torrent[:name]}, #{torrent[:year]}"
        %td
          =torrent[:files_number]
        %td
          =torrent[:quality]