config/routes.rb
#require 'tail'

ContentManagement::Application.routes.draw do
  resources :video_files

  get "stats/choose_dates"
  get "stats/results"
  devise_for :users

  get 'redirector', to: 'outgrader#get_redirect', format: 'js'
  #get 'outgrader/get_redirect'
  get 'outgrader' => 'outgrader#index'
  get 'outgrader/start'
  get 'outgrader/stop'
  get 'outgrader/restart'
  get 'outgrader/kill'
  get 'outgrader/get_config'
  post 'outgrader/outgrader_change_ip'
  post 'outgrader/redirector_change_ip'
  post 'outgrader/change_config'

  #get 'visits/send_click'
  post 'visits/send_click'
  get 'visits' => 'visits#index'
  #get 'visits/send_visit'
  post 'visits/send_visit'
  get 'visits/downloads'
  get 'visits/most_wanted'
  get 'visits/graph'
  get 'visits/torrents'


  mount Tail::Engine, at: '/tail'

  resources :sites

  resources :links

  resources :contents do
    member do
      post 'add_link' => 'contents#add_link'

    end
    collection do
      get 'create_with_kinopoisk' => 'contents#create_with_kinopoisk'
    end
  end

  root 'contents#index'

end

app/controllers/outgrader_controller.rb
require 'pp'
require 'net/http'
require 'watir-webdriver'
require 'date'
require 'headless'

class OutgraderController < ApplicationController
  skip_before_action :verify_authenticity_token, only: [:get_redirect]

  def initialize
    @outgrader = Param.first || Param.create
    super
  end

  def get_redirect
    begin
      url = @_request.env["HTTP_REFERER"]
      url+='/' unless url.end_with?('/')
      site = Link.find_site(url)

      if site.nil? || url.match(site.regexp).nil?
        render text: nil
        return
      end

      link = Link.find_by(url: url)
      content = nil
      if link.present?
        content = link.content
      else
        content = site.standard? ? Content.create_with_kinopoisk(url) : Content.find_content(url, site)
      end

      @site = site
      if content.present? && !content.video_files.empty?
        @href = content_url(content)
      else
        @href = nil
      end
    rescue
      @site = nil
      @href = nil
    end
    @request = request
    response.headers['Access-Control-Allow-Origin'] = '*'
    render action: :get_redirect, layout: nil
  end

  def index
    begin
      @config_hash = get_action(:config).merge(get_action(:'redirector/config'))
      @state_hash = get_action(:state).merge(get_action(:version))

      @state_hash['startDate'] = pluck_date(@state_hash['startDate'])
      @state_hash['activationDate'] = pluck_date(@state_hash['activationDate'])
      @state_hash['buildDate'] = pluck_date(@state_hash['buildDate'])

      @outgrader.update(outgrader_status: @state_hash[:state])
    rescue
      @config_hash = @state_hash = Hash.new
      flash[:alert]= 'Сервер недоступен'
    end
  end

  def pluck_date(timestamp)
    return DateTime.strptime(timestamp.to_s, '%Q').strftime('%d/%m/%Y %T')
  end

  def get_action(action)
    port = @outgrader.outgrader_port
    ip = @outgrader.outgrader_ip
    uri = URI("http://#{ip}:#{port}/#{action}")
    response = Net::HTTP.get uri

    return ActiveSupport::JSON.decode response
  end

  def change_config
    begin
      port = @outgrader.outgrader_port
      ip = @outgrader.outgrader_ip

      uri = URI("http://#{ip}:#{port}/#{:change_config}")
      Net::HTTP.post_form uri, params
      #rescue
      #  redirect_to outgrader_path, alert: 'Сервер не отвечает'
      #  return
    end
    redirect_to outgrader_path, notice: 'Настройки изменены'
  end

  def start
    put_action('start')
    redirect_to outgrader_path, notice: 'Outgrader запущен'
  end

  def stop
    put_action('stop')
    redirect_to outgrader_path, notice: 'Outgrader остановлен'
  end

  def restart
    put_action('restart')
    redirect_to outgrader_path, notice: 'Outgrader перезапущен'
  end

  def kill
    put_action('kill')
    redirect_to outgrader_path, notice: 'Outgrader принудительно остановлен'
  end

  def put_action(action)
    begin
      port = @outgrader.outgrader_port
      ip = @outgrader.outgrader_ip
      Net::HTTP.get(URI("http://#{ip}:#{port}/#{action}"))
    rescue
    end
  end

  def outgrader_change_ip
    @outgrader.update(outgrader_ip: params[:ip].gsub('http://', ''), outgrader_port: params[:port])
    redirect_to outgrader_path, notice: 'Адрес изменен'
  end

  def redirector_change_ip
    begin
      @outgrader.update(redirector_ip: params[:ip].gsub('http://', ''))
    rescue
      redirect_to outgrader_path, alert: 'Ошибка изменения адреса'
    end
    redirect_to outgrader_path, notice: 'Адрес изменен'
  end

end

app/helpers/outgrader_helper.rb
module OutgraderHelper
end

app/views/outgrader/get_redirect.haml
var redirector_url = "#{Param.first.redirector_ip}";
-if @site.present?
  var r;
  var isExecuted = false;
  var name_css = "#{@site.name_css}";
  var year_css = "#{@site.year_css}";
-if @href.present?
  var href = "#{@href}";
-else
  var href = null;
\function sendRequest(action, url, name_css, year_css) {
\    if (window.XMLHttpRequest) {r = new XMLHttpRequest();
\    } else if (window.ActiveXObject) { // IE
\        try {r = new ActiveXObject('Msxml2.XMLHTTP');}
\        catch (e) {
\            try {r = new ActiveXObject('Microsoft.XMLHTTP');}
\            catch (e) {}
\        }
\    }
\    if (!r) {return false;}
\    r.open('POST', 'http://' + redirector_url + '/visits/'
\        + action + '.js?url=' + url
\        + '&name=' + encodeURIComponent(document.querySelector(name_css).innerHTML)
\        + '&year=' + encodeURIComponent(document.querySelector(year_css).innerHTML));
\    r.onreadystatechange = function () {
\        if (r.readyState != 4 || r.status != 200) return;
\        console.log('Success: ' + r.responseText);
\    };
\    r.send();
\    return true;
\}
\
\function sendClick(url, name_css, year_css) {
\    sendRequest('send_click', url, name_css, year_css)
\}
\
\function sendVisit(url, name_css, year_css) {
\    sendRequest('send_visit', url, name_css, year_css)
\}
\
\function executeIt(){
\    isExecuted = true;
\    if (href != null) addButton();
\    sendVisit(location.href, name_css, year_css);
\}
\document.onreadystatechange = function () {
\    if (document.readyState == 'interactive') {
\        executeIt();
\    }
\}
\if (((document.readyState == 'complete') || (document.readyState == 'interactive') ) && !isExecuted) executeIt();

=@site.banner.html_safe if @site.present?

app/views/outgrader/index.html.haml
%h3 Статистика

-is_started = @state_hash['state'] == 'ACTIVE'? true : false

.form-actions
  = link_to 'Старт', outgrader_start_path, class: 'btn', disabled: is_started
  = link_to 'Стоп', outgrader_stop_path, class: 'btn', disabled: !is_started
  = link_to 'Перезапуск', outgrader_restart_path, class: 'btn', disabled: !is_started
  = link_to 'Принудительная остановка', outgrader_kill_path, class: 'btn', disabled: !is_started

%hr

%table.table.table-bordered.table-condensed
  -@state_hash.keys.each do |key|
    %tr
      %td
        %strong
          =key unless key=='threadInfo'
      %td
        =@state_hash[key] unless key=='threadInfo'
%hr

= form_tag outgrader_change_config_path, class: 'form-horizontal' do
  -@config_hash.keys.each do |key|
    .control-group
      =label_tag key, key, class: 'control-label'
      .span1
      .controls
        =text_field_tag key, @config_hash[key], class: 'text_field input-xxlarge'
  .form-actions
    .span1
    =submit_tag 'Изменить настройки', class: 'btn'
%hr

= form_tag outgrader_outgrader_change_ip_path, class: 'form-horizontal' do
  .control-group
    =label_tag 'Сервер статистики', nil, class: 'control-label'
    .controls
      =text_field_tag :ip, @outgrader.outgrader_ip, class: 'text_field'
  .control-group
    =label_tag 'Порт', nil, class: 'control-label'
    .controls
      =text_field_tag :port, @outgrader.outgrader_port, class: 'text_field'
  .form-actions
    =submit_tag 'Изменить', class: 'btn'
%hr

= form_tag outgrader_redirector_change_ip_path, class: 'form-horizontal' do
  .control-group
    =label_tag 'Сервер перенаправления', nil, class: 'control-label'
    .controls
      =text_field_tag :ip, @outgrader.redirector_ip, class: 'text_field'
  .form-actions
    =submit_tag 'Изменить', class: 'btn'
%hr

-if @state_hash['threadInfo'].present?
  %table.table.table-bordered.table-condensed
    %thead
      -@state_hash['threadInfo'][0].keys.each do |key|
        %th
          =key
    %tbody
      -@state_hash['threadInfo'].reverse.each do |row|
        %tr
          -row.keys.each do |key|
            %td
              =row[key]
%hr