config/routes.rb
#require 'tail'

ContentManagement::Application.routes.draw do
  resources :video_files

  get "stats/choose_dates"
  get "stats/results"
  devise_for :users

  get 'redirector', to: 'outgrader#get_redirect', format: 'js'
  #get 'outgrader/get_redirect'
  get 'outgrader' => 'outgrader#index'
  get 'outgrader/start'
  get 'outgrader/stop'
  get 'outgrader/restart'
  get 'outgrader/kill'
  get 'outgrader/get_config'
  post 'outgrader/outgrader_change_ip'
  post 'outgrader/redirector_change_ip'
  post 'outgrader/change_config'

  #get 'visits/send_click'
  post 'visits/send_click'
  get 'visits' => 'visits#index'
  #get 'visits/send_visit'
  post 'visits/send_visit'
  get 'visits/downloads'
  get 'visits/most_wanted'
  get 'visits/graph'
  get 'visits/torrents'


  mount Tail::Engine, at: '/tail'

  resources :sites

  resources :links

  resources :contents do
    member do
      post 'add_link' => 'contents#add_link'

    end
    collection do
      get 'create_with_kinopoisk' => 'contents#create_with_kinopoisk'
    end
  end

  root 'contents#index'

end

app/views/layouts/application.html.haml
!!! 5
%html(lang="ru")
  %head
    %title
      =content_for :title
    =stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true
    =javascript_include_tag "application", "data-turbolinks-track" => true
    =csrf_meta_tags

  %body
    .navbar.navbar-fixed-top
      .navbar-inner
        .container
          %a.btn.btn-navbar(data-target=".nav-collapse" data-toggle="collapse")
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.brand{href: root_path} Content management
          .container.nav-collapse
            %ul.nav
              %li= link_to 'Фильмы', contents_path
              - if user_signed_in?
                %li= link_to 'Сайты', sites_path
                %li= link_to 'Внешние ссылки', links_path
                %li= link_to 'Статистика', visits_path
                %li= link_to 'Скачивания', visits_downloads_path
                %li= link_to 'Most Wanted', visits_most_wanted_path
                %li= link_to 'Прокси', outgrader_path
                %li= link_to 'Торренты', visits_torrents_path
            - if user_signed_in?
              %ul.nav.pull-right
                %li= link_to 'Выход', destroy_user_session_path, :method => :delete
    .container
      .content
        .row
          .span12
            - if !flash[:notice].nil?
              .alert.alert-success
                %button.close(type="button" data-dismiss="alert")
                  &times;
                = flash[:notice]
            - if !flash[:alert].nil?
              .alert.alert-error
                %button.close(type="button" data-dismiss="alert")
                  &times;
                = flash[:alert]
            = yield